spring.datasource.url=jdbc:postgresql://localhost:6541/shareit
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=shareit
spring.datasource.password=shareit

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

server.ssl.enabled=false

spring.jpa.open-in-view=false

logging.level.org.zalando.logbook=TRACE